project_id = "feltwsxfnsvtnjqgmvie"

[functions.ingest-crime-data]
verify_jwt = false

[functions.performance-metrics]
verify_jwt = false

[functions.ml-predict]
verify_jwt = false

[functions.ml-analytics]
verify_jwt = false